#!/usr/bin/env python3

"""practice in daily but will delete work
before end of the day
"""
import subprocess

#output = subprocess.run(["ping", "-c 5" "192.168.4.238"])
#print(output)

one = "player 1 wins"
two = "player 2 wins"
done = 0
options = "rock, paper, or scissors?: "
player1 = input(options)
player2 = input(options)


if player1 == player2:
    print('its a tie')
elif player1 == 'rock' and player2 == 'paper':
    print(one)
elif player1 == 'rock' and player2 == 'scissors':
    print(one)
elif player1 == 'paper' and player2 == 'rock':
    print(two)
elif player1 == 'paper' and player2 == 'scissors':
    print(two)
elif player1 == 'scissors' and player2 == 'rock':
    print(two)
elif player1 == 'sissors' and player2 == 'paper'
    print(one)
