#!/usr/bin/env python3

import random

#random number
num = random.randint(50, 100)
print(num)

#random option
chips = ['hot fries', 'takis', 'pringles', 'ruffles']
types = random.choice(chips)
print(chips)




