#!/usr/bin/env python3

import random


top = input("type a number: ")

if top.isdigit():
    top = int(top)
    if top <= 0:
        print('number needs to be greater than 0')
        quit()
else:
    print('type in number next time')




random_number = random.randint(0, top)
guesses = 0

while True:
    guesses += 1
    ur_guess = input('make a guess: ')
    if ur_guess.isdigit():
        ur_guess = int(ur_guess)
    else:
        print('type a number gosh darn!')
        continue
    if ur_guess == random_number:
        print('lucky guess')
        break
    elif ur_guess < random_number:
        print('your guess is too LOW')
    elif ur_guess > random_number:
        print('you guess is too BIG')

print('it took you', guesses, 'guesses')


